package agents

import (
	"context"
	"time"

	"trade-machine/models"

	"github.com/shopspring/decimal"
)

// AgentMetadata provides information about an agent's capabilities
type AgentMetadata struct {
	Description      string   // Human-readable description of what the agent does
	Version          string   // Agent version for tracking changes
	RequiredServices []string // List of external services the agent depends on
}

// Agent interface that all analysts implement
type Agent interface {
	Analyze(ctx context.Context, symbol string) (*Analysis, error)
	Name() string
	Type() models.AgentType

	// Introspection methods
	IsAvailable(ctx context.Context) bool // Check if agent dependencies are healthy
	GetMetadata() AgentMetadata           // Get agent capabilities and requirements
}

// Analysis result from an agent
type Analysis struct {
	Symbol     string
	AgentType  models.AgentType
	Score      float64 // -100 to +100 (negative = bearish, positive = bullish)
	Confidence float64 // 0 to 100
	Reasoning  string
	Data       map[string]interface{} // Agent-specific data
	Timestamp  time.Time
}

// Recommendation generated by Portfolio Manager
type Recommendation struct {
	Symbol           string
	Action           models.RecommendationAction
	Quantity         decimal.Decimal
	TargetPrice      decimal.Decimal
	Confidence       float64
	Reasoning        string
	FundamentalScore float64
	SentimentScore   float64
	TechnicalScore   float64
}

// ScoreToAction converts a numerical score to a recommendation action
func ScoreToAction(score float64) models.RecommendationAction {
	if score > 25 {
		return models.RecommendationActionBuy
	}
	if score < -25 {
		return models.RecommendationActionSell
	}
	return models.RecommendationActionHold
}

// NormalizeScore ensures a score is within the -100 to +100 range
func NormalizeScore(score float64) float64 {
	if score > 100 {
		return 100
	}
	if score < -100 {
		return -100
	}
	return score
}

// NormalizeConfidence ensures confidence is within 0 to 100 range
func NormalizeConfidence(confidence float64) float64 {
	if confidence > 100 {
		return 100
	}
	if confidence < 0 {
		return 0
	}
	return confidence
}
