// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeStock(arg1) {
  return window['go']['main']['App']['AnalyzeStock'](arg1);
}

export function ApproveRecommendation(arg1) {
  return window['go']['main']['App']['ApproveRecommendation'](arg1);
}

export function GetAgentRuns(arg1) {
  return window['go']['main']['App']['GetAgentRuns'](arg1);
}

export function GetPendingRecommendations() {
  return window['go']['main']['App']['GetPendingRecommendations']();
}

export function GetPositions() {
  return window['go']['main']['App']['GetPositions']();
}

export function GetRecommendations(arg1) {
  return window['go']['main']['App']['GetRecommendations'](arg1);
}

export function GetTrades(arg1) {
  return window['go']['main']['App']['GetTrades'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RejectRecommendation(arg1) {
  return window['go']['main']['App']['RejectRecommendation'](arg1);
}
