// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AnalyzeStock(arg1:string):Promise<models.Recommendation>;

export function ApproveRecommendation(arg1:string):Promise<void>;

export function GetAgentRuns(arg1:number):Promise<Array<models.AgentRun>>;

export function GetPendingRecommendations():Promise<Array<models.Recommendation>>;

export function GetPositions():Promise<Array<models.Position>>;

export function GetRecommendations(arg1:number):Promise<Array<models.Recommendation>>;

export function GetTrades(arg1:number):Promise<Array<models.Trade>>;

export function Greet(arg1:string):Promise<string>;

export function RejectRecommendation(arg1:string):Promise<void>;
